"""Orchestrates the 5-step onboarding flow."""
from __future__ import annotations

import logging
import os
import re
import threading
from pathlib import Path

from core.interface.config import PROJECT_ROOT

log = logging.getLogger(__name__)
_env_lock = threading.Lock()
_SAFE_NAME_RE = re.compile(r"^[a-zA-Z0-9:._\-/ ]+$")

ENV_FILE = PROJECT_ROOT / ".env"
PROVIDERS_TOML = PROJECT_ROOT / "providers.toml"
BACKEND_PORTS = {"ollama": 11434, "lm-studio": 1234, "llama-cpp": 8080, "vllm": 8000, "sglang": 30000, "tabbyapi": 5000}


def save_model_selection(provider: str, model: str) -> None:
    from core.interface.settings import update_setting
    update_setting("provider_default", provider)
    update_setting("inference_model", model)


def save_provider_key(provider: str, api_key: str) -> None:
    key_map = {"anthropic": "ANTHROPIC_API_KEY", "openai": "OPENAI_API_KEY", "gemini": "GEMINI_API_KEY"}
    env_var = key_map.get(provider)
    if not env_var:
        raise ValueError(f"Unknown provider: {provider}")

    os.environ[env_var] = api_key

    lines = []
    if ENV_FILE.exists():
        lines = ENV_FILE.read_text(encoding="utf-8").splitlines()

    prefix = f"{env_var}="
    if any(line.startswith(prefix) for line in lines):
        lines = [f"{prefix}{api_key}" if line.startswith(prefix) else line for line in lines]
    else:
        lines.append(f"{prefix}{api_key}")

    with _env_lock:
        ENV_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def test_provider_connection(provider: str, api_key: str) -> dict:
    import httpx
    try:
        if provider == "anthropic":
            resp = httpx.get("https://api.anthropic.com/v1/models",
                           headers={"x-api-key": api_key, "anthropic-version": "2023-06-01"}, timeout=10)
        elif provider == "openai":
            resp = httpx.get("https://api.openai.com/v1/models",
                           headers={"Authorization": f"Bearer {api_key}"}, timeout=10)
        elif provider == "gemini":
            resp = httpx.get("https://generativelanguage.googleapis.com/v1beta/models",
                           headers={"x-goog-api-key": api_key}, timeout=10)
        else:
            return {"success": False, "message": f"Unknown provider: {provider}"}
        if resp.status_code == 200:
            return {"success": True, "message": "Connected"}
        return {"success": False, "message": f"HTTP {resp.status_code}"}
    except httpx.HTTPError:
        return {"success": False, "message": "Connection failed"}


def write_providers_toml(local_provider: str = "ollama", local_model: str = "qwen2.5:14b",
                         cloud_providers: list[str] | None = None,
                         detected_backends: list[dict] | None = None) -> None:
    if PROVIDERS_TOML.exists():
        return
    # Validate inputs to prevent TOML injection
    if local_provider not in BACKEND_PORTS:
        local_provider = "ollama"
    if not _SAFE_NAME_RE.match(local_model):
        local_model = "qwen2.5:14b"

    sections = [f"# Generated by oikOS onboarding\n[general]\ndefault_provider = \"{local_provider}\"\ncloud_fallback = true\n"]

    if detected_backends:
        for db in detected_backends:
            name = db.get("backend", "ollama")
            if name not in BACKEND_PORTS:
                continue
            port = db.get("port", BACKEND_PORTS.get(name, 11434))
            models = db.get("models", [])
            model = models[0]["name"] if models and _SAFE_NAME_RE.match(models[0].get("name", "")) else "unknown"
            entry = f"\n[providers.{name}]\nenabled = true\nbase_url = \"http://localhost:{port}\"\ndefault_model = \"{model}\"\n"
            if name != "ollama":
                entry = f"\n[providers.{name}]\nenabled = true\ntype = \"openai-local\"\nbase_url = \"http://localhost:{port}\"\ndefault_model = \"{model}\"\n"
            sections.append(entry)
    else:
        port = BACKEND_PORTS.get(local_provider, 11434)
        sections.append(f"\n[providers.{local_provider}]\nenabled = true\nbase_url = \"http://localhost:{port}\"\ndefault_model = \"{local_model}\"\n")

    for cp in (cloud_providers or []):
        key_map = {"anthropic": "ANTHROPIC_API_KEY", "openai": "OPENAI_API_KEY", "gemini": "GEMINI_API_KEY"}
        model_map = {"anthropic": "claude-sonnet-4-20250514", "openai": "gpt-4o", "gemini": "gemini-2.5-pro"}
        if cp in key_map:
            sections.append(f"\n[providers.{cp}]\nenabled = true\napi_key_env = \"{key_map[cp]}\"\ndefault_model = \"{model_map[cp]}\"\n")
    PROVIDERS_TOML.write_text("\n".join(sections).strip() + "\n", encoding="utf-8")
