[headers]
anthropic-beta = "claude-code-20250219"
anthropic-version = "2023-06-01"
user-agent = "claude-code/2.1.81"

[oauth]
client-id = "9d1c250a-e61b-44d9-88ed-5944d1962f5e"
token-url = "https://api.anthropic.com/v1/oauth/token"
